import os
import sys
import pandas as pd

# Add the src directory to sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.join(current_dir, "src")
sys.path.append(src_dir)

from data_loader import DataLoader
from volume_confirmation_engine import VolumeConfirmationEngine

def main():
    filepath = os.path.join(current_dir, "sample_data.csv")

    if not os.path.isfile(filepath):
        print(f"🚫 File not found: {filepath}")
        return

    loader = DataLoader(filepath)
    df = loader.load_data()

    # 🧹 Ensure correct types
    df['price'] = pd.to_numeric(df['price'], errors='coerce')
    df['volume'] = pd.to_numeric(df['volume'], errors='coerce')
    df.dropna(subset=['price', 'volume'], inplace=True)

    if df.empty or df.shape[0] < 30:
        print("⚠️ Not enough valid data to run volume analysis.")
        return

    engine = VolumeConfirmationEngine()
    try:
        result = engine.run_analysis(df)
    except Exception as e:
        print(f"❌ Error during volume analysis: {e}")
        return

    if result is None or result.empty:
        print("❌ No result generated by VolumeConfirmationEngine.")
        return

    print("📊 Volume Analysis Result (Last 10 rows):")
    print(result.tail(10))

if __name__ == "__main__":
    main()